# Generated by Django 4.0.5 on 2022-07-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_rename_contactus_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
    ]
