# Generated by Django 4.0.5 on 2022-07-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
    ]
