# Generated by Django 4.0.5 on 2022-07-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_remove_aboutus_columnae_remove_aboutus_succolumnae_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='Second_subject',
            new_name='second_subject',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='column2',
            field=models.TextField(blank=True, null=True, verbose_name=' توضیحات ردیف دوم'),
        ),
    ]
