# Generated by Django 4.0.5 on 2022-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_rename_second_subject_aboutus_second_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='لینک فیسبوک'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='لینک توییتر'),
        ),
    ]
