# Generated by Django 4.0.5 on 2022-07-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0015_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map_address',
            field=models.GenericIPAddressField(),
        ),
    ]
