# Generated by Django 4.0.5 on 2022-06-27 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_rename_author_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 15, 14, 24, 374228, tzinfo=utc)),
        ),
    ]
