# Generated by Django 4.0.5 on 2022-06-27 15:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0004_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date='pub_date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 15, 20, 44, 361436, tzinfo=utc)),
        ),
    ]
