# Generated by Django 4.0.5 on 2022-06-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Test',
            field=models.URLField(null=True),
        ),
    ]
