# Generated by Django 4.0.5 on 2022-06-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_remove_article_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Test',
            field=models.BinaryField(null=True),
        ),
    ]
