# Generated by Django 4.0.5 on 2022-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_article_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Test',
            field=models.FileField(null=True, upload_to='test'),
        ),
    ]
