# Generated by Django 4.0.5 on 2022-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_remove_article_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
