# Generated by Django 4.0.5 on 2022-06-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_article_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Status',
            new_name='Release_Status',
        ),
    ]
