# Generated by Django 4.0.5 on 2022-06-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_rename_status_article_release_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Release_Status',
            field=models.BooleanField(default=False),
        ),
    ]
