# Generated by Django 4.0.5 on 2022-07-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_alter_article_release_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
