# Generated by Django 4.0.5 on 2022-07-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Slug',
            new_name='slug',
        ),
    ]
