# Generated by Django 4.0.5 on 2022-07-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_alter_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-Updated',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
