# Generated by Django 4.0.5 on 2022-07-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_alter_article_options_alter_article_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
