# Generated by Django 4.0.5 on 2022-07-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
