# Generated by Django 4.0.5 on 2022-07-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0023_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(related_name='articles', to='blog_app.category'),
        ),
    ]
