# Generated by Django 4.0.5 on 2022-07-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0035_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Body',
            field=models.TextField(verbose_name='متن مقاله'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='متن نظر'),
        ),
    ]
