# Generated by Django 4.0.5 on 2022-07-29 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0038_alter_like_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(related_name='blog_likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک '),
        ),
    ]
