# Generated by Django 4.0.5 on 2022-07-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0039_article_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
